// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_stocks_service.proto

package com.example.grpcjavago.grpc;

public final class GrpcStockServiceProto {
  private GrpcStockServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grp_stock_service_stockUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grp_stock_service_stockUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grp_stock_service_stockUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grp_stock_service_stockUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031grpc_stocks_service.proto\022\021grp_stock_s" +
      "ervice\"\"\n\022stockUpdateRequest\022\014\n\004name\030\001 \001" +
      "(\t\"7\n\023stockUpdateResponse\022\014\n\004name\030\001 \001(\t\022" +
      "\022\n\nstockValue\030\002 \001(\0052t\n\014StockService\022d\n\017G" +
      "etStockUpdates\022%.grp_stock_service.stock" +
      "UpdateRequest\032&.grp_stock_service.stockU" +
      "pdateResponse\"\0000\001BH\n\033com.example.grpcjav" +
      "ago.grpcB\025GrpcStockServiceProtoP\001Z\020go_se" +
      "rver/serverb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grp_stock_service_stockUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grp_stock_service_stockUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grp_stock_service_stockUpdateRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_grp_stock_service_stockUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grp_stock_service_stockUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grp_stock_service_stockUpdateResponse_descriptor,
        new java.lang.String[] { "Name", "StockValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
