// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_stocks_service.proto

package com.example.grpcjavago.grpc;

public interface stockUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grp_stock_service.stockUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 stockValue = 2;</code>
   */
  int getStockValue();
}
